#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/work/y/ywng/workspace/DijetISR-Resolved/r21StatisticalAna/source/LogFiles/dijetgamma_data_hist_20160727_15p45fb_4Par_169_1493/Step2_setLimitsOneMassPoint/ScriptArchive/Step2_BatchScript_Template_ZPrime0p10250_15p45fb_1.sh'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
